version: "3.8"

services:
  # custom image
  app:
    build:
      args:
        user: jardel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: especializati/laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    depends_on:
      - redis
      - queue
    networks:
      - laravel
  
  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8989:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - 3388:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
  
  # redis
  redis:
    image: redis:latest
    networks:
      - laravel

  # queue
  queue:
    build:
      args:
        user: jardel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel

networks:
  laravel:
    driver: bridge